### ISSUE TITLE
The links to set up a working environment, Coding Guidelines and issues in CONTRIBUTING.md are not available

### ISSUE THREAD

**Issue by AbdallahKhaled93** [eclipse-openbsw/openbsw#22]
Hello,

I wanted to start contributing to the openbsw project and I was checking the CONTRIBUTING.md page to follow the steps and familiarize myself with the rules.
I tried clicking on **set up a working environment**, **Coding Guidelines** and **issues** but 'I got Site Not Found'

Is the project open yet for contribution ?
If yes, is it possible to proivde how to set it up on a linux PC ?
Thanks

**Comment by ThoFrank** [comment]
Hi,

great to hear that! We recently moved the documentation into a new subdirectory and didn't update the links in ``CONTRIBUTING.md``. Thanks for pointing that out. I'll fix it.

Here are the correct links:
https://eclipse-openbsw.github.io/openbsw/sphinx_docs/doc/learning/setup/index.html
https://eclipse-openbsw.github.io/openbsw/sphinx_docs/doc/codingGuidelines/index.html

**Comment by AbdallahKhaled93** [comment]
Thank you.
