### ISSUE TITLE
C++20 support

### ISSUE THREAD

**Issue by rolandreichweinbmw** [eclipse-openbsw/openbsw#7]
When porting (compatibly) from C++14 to C++20, I found that most prominently many previously valid uses of the volatile keyword are deprecated by C++20.

E.g. enforcing explicit read-modify-write on volatile variables to reflect separate memory accesses, as in: A |= 3; which would end up in A = A | 3;

In other cases in OpenBSW, volatile could be removed as in function return types, e.g. platforms/s32k1xx/bsp/bspInterruptsImpl/include/interrupts/suspendResumeAllInterrupts.h, and in platforms/s32k1xx/bsp/bspAdc/include/adc/Adc.h:251, where optimization-prevention is already ensured by the access to the still volatile variable fADC.SC1

I can prepare a pull request, but first wanted to discuss if C++20 support would be welcome at this point. Or if OpenBSW should stay C++14-only.

**Comment by marcmo** [comment]
I'd say the codebase should support **C++ 14** projects and thus the min. required C++ version should be 14. Nevertheless, it would be good to check with a **C++ 20** compiler if we are compatible and if new warnings can be avoided. So changes that do not sacrifice our **C++14** support would be possible!
